package com.itechro.iaml.commons.constants;

public class PrivilegeCode {

    public static final String IAML_SETTINGS_COMPANY_VIEW = "IAML.SETTINGS.COMPANY.VIEW";
    public static final String IAML_SETTINGS_COMPANY_ADD_EDIT = "IAML.SETTINGS.COMPANY.ADD.EDIT";
    public static final String IAML_SETTINGS_USER_VIEW = "IAML.SETTINGS.USER.VIEW";
    public static final String IAML_SETTINGS_USER_ADD_EDIT = "IAML.SETTINGS.USER.ADD.EDIT";
    public static final String IAML_SETTINGS_ROLE_VIEW = "IAML.SETTINGS.ROLE.VIEW";
    public static final String IAML_SETTINGS_ROLE_ADD_EDIT = "IAML.SETTINGS.ROLE.ADD.EDIT";
    public static final String IAML_SETTINGS_USER_GROUP_VIEW = "IAML.SETTINGS.USER.GROUP.VIEW";
    public static final String IAML_SETTINGS_USER_GROUP_ADD_EDIT = "IAML.SETTINGS.USER.GROUP.ADD.EDIT";

    public static final String IAML_BUSINESS_LOCATION_VIEW = "IAML.BUSINESS.LOCATION.VIEW";
    public static final String IAML_BUSINESS_LOCATION_ADD_EDIT = "IAML.BUSINESS.LOCATION.ADD.EDIT";
    public static final String IAML_BUSINESS_BUSINESS_UNIT_VIEW = "IAML.BUSINESS.BUSINESS.UNIT.VIEW";
    public static final String IAML_BUSINESS_BUSINESS_UNIT_ADD_EDIT = "IAML.BUSINESS.BUSINESS.UNIT.ADD.EDIT";
    public static final String IAML_BUSINESS_SUB_BUSINESS_UNIT_VIEW = "IAML.BUSINESS.SUB.BUSINESS.UNIT.VIEW";
    public static final String IAML_BUSINESS_SUB_BUSINESS_UNIT_ADD_EDIT = "IAML.BUSINESS.SUB.BUSINESS.UNIT.ADD.EDIT";
    public static final String IAML_BUSINESS_PRODUCT_VIEW = "IAML.BUSINESS.PRODUCT.VIEW";
    public static final String IAML_BUSINESS_PRODUCT_ADD_EDIT = "IAML.BUSINESS.PRODUCT.ADD.EDIT";
    public static final String IAML_BUSINESS_SUPERVISOR_VIEW = "IAML.BUSINESS.SUPERVISOR.VIEW";
    public static final String IAML_BUSINESS_SUPERVISOR_ADD_EDIT = "IAML.BUSINESS.SUPERVISOR.ADD.EDIT";
    public static final String IAML_BUSINESS_MEASURE_UNIT_CATEGORY_VIEW = "IAML.BUSINESS.MEASURE.UNIT.CATEGORY.VIEW";
    public static final String IAML_BUSINESS_MEASURE_UNIT_CATEGORY_ADD_EDIT = "IAML.BUSINESS.MEASURE.UNIT.CATEGORY.ADD.EDIT";
    public static final String IAML_BUSINESS_MEASURE_UNIT_VIEW = "IAML.BUSINESS.MEASURE.UNIT.VIEW";
    public static final String IAML_BUSINESS_MEASURE_UNIT_ADD_EDIT = "IAML.BUSINESS.MEASURE.UNIT.ADD.EDIT";
    public static final String IAML_BUSINESS_MEASURE_VIEW = "IAML.BUSINESS.MEASURE.VIEW";
    public static final String IAML_BUSINESS_MEASURE_ADD_EDIT = "IAML.BUSINESS.MEASURE.ADD.EDIT";
    public static final String IAML_BUSINESS_MEASURE_GROUP_VIEW = "IAML.BUSINESS.MEASURE.GROUP.VIEW";
    public static final String IAML_BUSINESS_MEASURE_GROUP_ADD_EDIT = "IAML.BUSINESS.MEASURE.GROUP.ADD.EDIT";
    public static final String IAML_BUSINESS_PROCESS_TEMPLATE_VIEW = "IAML.BUSINESS.PROCESS.TEMPLATE.VIEW";
    public static final String IAML_BUSINESS_PROCESS_TEMPLATE_ADD_EDIT = "IAML.BUSINESS.PROCESS.TEMPLATE.ADD.EDIT";
    public static final String IAML_BUSINESS_PROCESS_VIEW = "IAML.BUSINESS.PROCESS.VIEW";
    public static final String IAML_BUSINESS_PROCESS_ADD_EDIT = "IAML.BUSINESS.PROCESS.ADD.EDIT";
    public static final String IAML_REPORT_TEMPLATE_VIEW = "IAML.REPORT.TEMPLATE.VIEW";
    public static final String IAML_REPORT_TEMPLATE_ADD_EDIT = "IAML.REPORT.TEMPLATE.ADD.EDIT";
    public static final String IAML_REPORT_GENERATOR_VIEW = "IAML.REPORT.GENERATOR.VIEW";
    public static final String IAML_REPORT_GENERATOR_REPORT = "IAML.REPORT.GENERATOR.REPORT";
    public static final String IAML_BUSINESS_WIDGET_ADD_EDIT = "IAML.BUSINESS.WIDGET.ADD.EDIT";
    public static final String IAML_REPORT_SCHEDULER_ADD_EDIT = "IAML.REPORT.SCHEDULER.ADD.EDIT";



    public static final String IAML_BUSINESS_PROCESS_UPLOAD_DATA_ENTRY_FORM_WITH_ADD_EDIT_TARGET_BUDGET = "IAML.BUSINESS.PROCESS.UPLOAD.DATA.ENTRY.FORM.WITH.ADD.EDIT.TARGET.BUDGET";

}
